//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetcityAnnunciator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int UpdateInterval {
            get {
                return ((int)(this["UpdateInterval"]));
            }
            set {
                this["UpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0:5;0:4;5:0;4:0;1:5;5:1")]
        public string RequeredGreenScore {
            get {
                return ((string)(this["RequeredGreenScore"]));
            }
            set {
                this["RequeredGreenScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Теннис")]
        public string Filter {
            get {
                return ((string)(this["Filter"]));
            }
            set {
                this["Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0:3;3:0;1:4;4:1;2:5;5:2")]
        public string RequeredYellowScore {
            get {
                return ((string)(this["RequeredYellowScore"]));
            }
            set {
                this["RequeredYellowScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0:2;2:0;1:3;3:1;2:4;4:2;3:5;5:3")]
        public string RequeredOrangeScore {
            get {
                return ((string)(this["RequeredOrangeScore"]));
            }
            set {
                this["RequeredOrangeScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnabledGreen {
            get {
                return ((bool)(this["EnabledGreen"]));
            }
            set {
                this["EnabledGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnabledYellow {
            get {
                return ((bool)(this["EnabledYellow"]));
            }
            set {
                this["EnabledYellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnabledOrange {
            get {
                return ((bool)(this["EnabledOrange"]));
            }
            set {
                this["EnabledOrange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuteAll {
            get {
                return ((bool)(this["MuteAll"]));
            }
            set {
                this["MuteAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SortingByColor {
            get {
                return ((bool)(this["SortingByColor"]));
            }
            set {
                this["SortingByColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Delay {
            get {
                return ((int)(this["Delay"]));
            }
            set {
                this["Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnabledBlue {
            get {
                return ((bool)(this["EnabledBlue"]));
            }
            set {
                this["EnabledBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"1,0:6&2,0:1;1,0:6&2,0:2;1,0:6&2,0:3;1,0:6&2,0:4;1,0:6&2,0:5;1,6:0&2,1:0;1,6:0&2,2:0;1,6:0&2,3:0;1,6:0&2,4:0;1,6:0&2,5:0;1,1:6&2,0:1;1,1:6&2,0:2;1,1:6&2,0:3;1,1:6&2,0:4;1,1:6&2,0:5;1,6:1&2,1:0;1,6:1&2,2:0;1,6:1&2,3:0;1,6:1&2,4:0;1,6:1&2,5:0;1,2:6&2,0:1;1,2:6&2,0:2;1,2:6&2,0:3;1,2:6&2,0:4;1,2:6&2,0:5;1,6:2&2,1:0;1,6:2&2,2:0;1,6:2&2,3:0;1,6:2&2,4:0;1,6:2&2,5:0")]
        public string RequiredBlueScore {
            get {
                return ((string)(this["RequiredBlueScore"]));
            }
            set {
                this["RequiredBlueScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuteBlue {
            get {
                return ((bool)(this["MuteBlue"]));
            }
            set {
                this["MuteBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuteGreen {
            get {
                return ((bool)(this["MuteGreen"]));
            }
            set {
                this["MuteGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuteYellow {
            get {
                return ((bool)(this["MuteYellow"]));
            }
            set {
                this["MuteYellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuteOrange {
            get {
                return ((bool)(this["MuteOrange"]));
            }
            set {
                this["MuteOrange"] = value;
            }
        }
    }
}
